// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/usecase/interfaces/input_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/usecase/interfaces/input_port.go -destination=internal/auth/usecase/interfaces/mocks/input_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/chuuch/expense-tracker-backend/internal/auth/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserUsecase is a mock of UserUsecase interface.
type MockUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseMockRecorder
	isgomock struct{}
}

// MockUserUsecaseMockRecorder is the mock recorder for MockUserUsecase.
type MockUserUsecaseMockRecorder struct {
	mock *MockUserUsecase
}

// NewMockUserUsecase creates a new mock instance.
func NewMockUserUsecase(ctrl *gomock.Controller) *MockUserUsecase {
	mock := &MockUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsecase) EXPECT() *MockUserUsecaseMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockUserUsecase) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserUsecaseMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserUsecase)(nil).DeleteUser), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserUsecase) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserUsecaseMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserUsecase)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserUsecase) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserUsecaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserUsecase)(nil).GetByID), ctx, id)
}

// Login mocks base method.
func (m *MockUserUsecase) Login(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserUsecaseMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserUsecase)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUserUsecase) Register(ctx context.Context, email, password, username, phone, address, city, state, zip, country string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password, username, phone, address, city, state, zip, country)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserUsecaseMockRecorder) Register(ctx, email, password, username, phone, address, city, state, zip, country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserUsecase)(nil).Register), ctx, email, password, username, phone, address, city, state, zip, country)
}

// UpdateUser mocks base method.
func (m *MockUserUsecase) UpdateUser(ctx context.Context, id, username, phone, address, city, state, zip, country string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, username, phone, address, city, state, zip, country)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserUsecaseMockRecorder) UpdateUser(ctx, id, username, phone, address, city, state, zip, country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserUsecase)(nil).UpdateUser), ctx, id, username, phone, address, city, state, zip, country)
}

// MockRefreshTokenUsecase is a mock of RefreshTokenUsecase interface.
type MockRefreshTokenUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenUsecaseMockRecorder
	isgomock struct{}
}

// MockRefreshTokenUsecaseMockRecorder is the mock recorder for MockRefreshTokenUsecase.
type MockRefreshTokenUsecaseMockRecorder struct {
	mock *MockRefreshTokenUsecase
}

// NewMockRefreshTokenUsecase creates a new mock instance.
func NewMockRefreshTokenUsecase(ctrl *gomock.Controller) *MockRefreshTokenUsecase {
	mock := &MockRefreshTokenUsecase{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenUsecase) EXPECT() *MockRefreshTokenUsecaseMockRecorder {
	return m.recorder
}

// DeleteExpired mocks base method.
func (m *MockRefreshTokenUsecase) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRefreshTokenUsecaseMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRefreshTokenUsecase)(nil).DeleteExpired), ctx)
}

// IssueTokenPair mocks base method.
func (m *MockRefreshTokenUsecase) IssueTokenPair(ctx context.Context, user *domain.User) (*domain.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokenPair", ctx, user)
	ret0, _ := ret[0].(*domain.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokenPair indicates an expected call of IssueTokenPair.
func (mr *MockRefreshTokenUsecaseMockRecorder) IssueTokenPair(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenPair", reflect.TypeOf((*MockRefreshTokenUsecase)(nil).IssueTokenPair), ctx, user)
}

// Refresh mocks base method.
func (m *MockRefreshTokenUsecase) Refresh(ctx context.Context, rawRefreshToken string) (*domain.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, rawRefreshToken)
	ret0, _ := ret[0].(*domain.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockRefreshTokenUsecaseMockRecorder) Refresh(ctx, rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockRefreshTokenUsecase)(nil).Refresh), ctx, rawRefreshToken)
}

// Revoke mocks base method.
func (m *MockRefreshTokenUsecase) Revoke(ctx context.Context, rawRefreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, rawRefreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenUsecaseMockRecorder) Revoke(ctx, rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenUsecase)(nil).Revoke), ctx, rawRefreshToken)
}
