// Code generated by MockGen. DO NOT EDIT.
// Source: internal/analytics/usecase/interfaces/input_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/analytics/usecase/interfaces/input_port.go -destination=internal/analytics/usecase/interfaces/mocks/input_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/chuuch/expense-tracker-backend/internal/analytics/usecase/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsUsecase is a mock of AnalyticsUsecase interface.
type MockAnalyticsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsUsecaseMockRecorder
	isgomock struct{}
}

// MockAnalyticsUsecaseMockRecorder is the mock recorder for MockAnalyticsUsecase.
type MockAnalyticsUsecaseMockRecorder struct {
	mock *MockAnalyticsUsecase
}

// NewMockAnalyticsUsecase creates a new mock instance.
func NewMockAnalyticsUsecase(ctrl *gomock.Controller) *MockAnalyticsUsecase {
	mock := &MockAnalyticsUsecase{ctrl: ctrl}
	mock.recorder = &MockAnalyticsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsUsecase) EXPECT() *MockAnalyticsUsecaseMockRecorder {
	return m.recorder
}

// GetMonthlySpending mocks base method.
func (m *MockAnalyticsUsecase) GetMonthlySpending(ctx context.Context, filter interfaces.MonthlySpendingFilter) ([]interfaces.MonthlySpendingPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlySpending", ctx, filter)
	ret0, _ := ret[0].([]interfaces.MonthlySpendingPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlySpending indicates an expected call of GetMonthlySpending.
func (mr *MockAnalyticsUsecaseMockRecorder) GetMonthlySpending(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlySpending", reflect.TypeOf((*MockAnalyticsUsecase)(nil).GetMonthlySpending), ctx, filter)
}

// GetSpendingByCategory mocks base method.
func (m *MockAnalyticsUsecase) GetSpendingByCategory(ctx context.Context, filter interfaces.CategorySpendingFilter) ([]interfaces.CategorySpendingPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpendingByCategory", ctx, filter)
	ret0, _ := ret[0].([]interfaces.CategorySpendingPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpendingByCategory indicates an expected call of GetSpendingByCategory.
func (mr *MockAnalyticsUsecaseMockRecorder) GetSpendingByCategory(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpendingByCategory", reflect.TypeOf((*MockAnalyticsUsecase)(nil).GetSpendingByCategory), ctx, filter)
}
