// Code generated by MockGen. DO NOT EDIT.
// Source: internal/analytics/usecase/interfaces/output_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/analytics/usecase/interfaces/output_port.go -destination=internal/analytics/usecase/interfaces/mocks/output_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/chuuch/expense-tracker-backend/internal/analytics/usecase/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// GetMonthlySpending mocks base method.
func (m *MockAnalyticsRepository) GetMonthlySpending(ctx context.Context, filter interfaces.MonthlySpendingFilter) ([]interfaces.MonthlySpendingPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlySpending", ctx, filter)
	ret0, _ := ret[0].([]interfaces.MonthlySpendingPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlySpending indicates an expected call of GetMonthlySpending.
func (mr *MockAnalyticsRepositoryMockRecorder) GetMonthlySpending(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlySpending", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetMonthlySpending), ctx, filter)
}

// GetSpendingByCategory mocks base method.
func (m *MockAnalyticsRepository) GetSpendingByCategory(ctx context.Context, filter interfaces.CategorySpendingFilter) ([]interfaces.CategorySpendingPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpendingByCategory", ctx, filter)
	ret0, _ := ret[0].([]interfaces.CategorySpendingPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpendingByCategory indicates an expected call of GetSpendingByCategory.
func (mr *MockAnalyticsRepositoryMockRecorder) GetSpendingByCategory(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpendingByCategory", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetSpendingByCategory), ctx, filter)
}
