// Code generated by MockGen. DO NOT EDIT.
// Source: internal/goals/usecase/interfaces/input_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/goals/usecase/interfaces/input_port.go -destination=internal/goals/usecase/interfaces/mocks/input_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/chuuch/expense-tracker-backend/internal/goals/domain"
	interfaces "github.com/chuuch/expense-tracker-backend/internal/goals/usecase/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockGoalUsecase is a mock of GoalUsecase interface.
type MockGoalUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGoalUsecaseMockRecorder
	isgomock struct{}
}

// MockGoalUsecaseMockRecorder is the mock recorder for MockGoalUsecase.
type MockGoalUsecaseMockRecorder struct {
	mock *MockGoalUsecase
}

// NewMockGoalUsecase creates a new mock instance.
func NewMockGoalUsecase(ctrl *gomock.Controller) *MockGoalUsecase {
	mock := &MockGoalUsecase{ctrl: ctrl}
	mock.recorder = &MockGoalUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoalUsecase) EXPECT() *MockGoalUsecaseMockRecorder {
	return m.recorder
}

// AddContribution mocks base method.
func (m *MockGoalUsecase) AddContribution(ctx context.Context, userID, goalID string, amount int64, contributionDate time.Time, note string) (*domain.GoalContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContribution", ctx, userID, goalID, amount, contributionDate, note)
	ret0, _ := ret[0].(*domain.GoalContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddContribution indicates an expected call of AddContribution.
func (mr *MockGoalUsecaseMockRecorder) AddContribution(ctx, userID, goalID, amount, contributionDate, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContribution", reflect.TypeOf((*MockGoalUsecase)(nil).AddContribution), ctx, userID, goalID, amount, contributionDate, note)
}

// CreateGoal mocks base method.
func (m *MockGoalUsecase) CreateGoal(ctx context.Context, userID, name, currency string, targetAmount int64, targetDate *time.Time) (*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGoal", ctx, userID, name, currency, targetAmount, targetDate)
	ret0, _ := ret[0].(*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGoal indicates an expected call of CreateGoal.
func (mr *MockGoalUsecaseMockRecorder) CreateGoal(ctx, userID, name, currency, targetAmount, targetDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGoal", reflect.TypeOf((*MockGoalUsecase)(nil).CreateGoal), ctx, userID, name, currency, targetAmount, targetDate)
}

// DeleteGoal mocks base method.
func (m *MockGoalUsecase) DeleteGoal(ctx context.Context, userID, goalID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGoal", ctx, userID, goalID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGoal indicates an expected call of DeleteGoal.
func (mr *MockGoalUsecaseMockRecorder) DeleteGoal(ctx, userID, goalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGoal", reflect.TypeOf((*MockGoalUsecase)(nil).DeleteGoal), ctx, userID, goalID)
}

// GetGoalByID mocks base method.
func (m *MockGoalUsecase) GetGoalByID(ctx context.Context, userID, goalID string) (*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalByID", ctx, userID, goalID)
	ret0, _ := ret[0].(*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoalByID indicates an expected call of GetGoalByID.
func (mr *MockGoalUsecaseMockRecorder) GetGoalByID(ctx, userID, goalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalByID", reflect.TypeOf((*MockGoalUsecase)(nil).GetGoalByID), ctx, userID, goalID)
}

// GetGoalProgress mocks base method.
func (m *MockGoalUsecase) GetGoalProgress(ctx context.Context, userID, goalID string) (*interfaces.GoalProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalProgress", ctx, userID, goalID)
	ret0, _ := ret[0].(*interfaces.GoalProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoalProgress indicates an expected call of GetGoalProgress.
func (mr *MockGoalUsecaseMockRecorder) GetGoalProgress(ctx, userID, goalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalProgress", reflect.TypeOf((*MockGoalUsecase)(nil).GetGoalProgress), ctx, userID, goalID)
}

// ListContributions mocks base method.
func (m *MockGoalUsecase) ListContributions(ctx context.Context, userID, goalID string, pageSize, offset int) ([]*domain.GoalContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContributions", ctx, userID, goalID, pageSize, offset)
	ret0, _ := ret[0].([]*domain.GoalContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContributions indicates an expected call of ListContributions.
func (mr *MockGoalUsecaseMockRecorder) ListContributions(ctx, userID, goalID, pageSize, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContributions", reflect.TypeOf((*MockGoalUsecase)(nil).ListContributions), ctx, userID, goalID, pageSize, offset)
}

// ListGoals mocks base method.
func (m *MockGoalUsecase) ListGoals(ctx context.Context, filter interfaces.GoalListFilter) ([]*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGoals", ctx, filter)
	ret0, _ := ret[0].([]*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGoals indicates an expected call of ListGoals.
func (mr *MockGoalUsecaseMockRecorder) ListGoals(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGoals", reflect.TypeOf((*MockGoalUsecase)(nil).ListGoals), ctx, filter)
}

// UpdateGoal mocks base method.
func (m *MockGoalUsecase) UpdateGoal(ctx context.Context, userID, goalID, name string, targetAmount int64, targetDate *time.Time, status domain.GoalStatus) (*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoal", ctx, userID, goalID, name, targetAmount, targetDate, status)
	ret0, _ := ret[0].(*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGoal indicates an expected call of UpdateGoal.
func (mr *MockGoalUsecaseMockRecorder) UpdateGoal(ctx, userID, goalID, name, targetAmount, targetDate, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoal", reflect.TypeOf((*MockGoalUsecase)(nil).UpdateGoal), ctx, userID, goalID, name, targetAmount, targetDate, status)
}
