// Code generated by MockGen. DO NOT EDIT.
// Source: internal/goals/usecase/interfaces/output_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/goals/usecase/interfaces/output_port.go -destination=internal/goals/usecase/interfaces/mocks/output_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/chuuch/expense-tracker-backend/internal/goals/domain"
	interfaces "github.com/chuuch/expense-tracker-backend/internal/goals/usecase/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockGoalRepository is a mock of GoalRepository interface.
type MockGoalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGoalRepositoryMockRecorder
	isgomock struct{}
}

// MockGoalRepositoryMockRecorder is the mock recorder for MockGoalRepository.
type MockGoalRepositoryMockRecorder struct {
	mock *MockGoalRepository
}

// NewMockGoalRepository creates a new mock instance.
func NewMockGoalRepository(ctrl *gomock.Controller) *MockGoalRepository {
	mock := &MockGoalRepository{ctrl: ctrl}
	mock.recorder = &MockGoalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoalRepository) EXPECT() *MockGoalRepositoryMockRecorder {
	return m.recorder
}

// CreateGoal mocks base method.
func (m *MockGoalRepository) CreateGoal(ctx context.Context, goal *domain.Goal) (*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGoal", ctx, goal)
	ret0, _ := ret[0].(*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGoal indicates an expected call of CreateGoal.
func (mr *MockGoalRepositoryMockRecorder) CreateGoal(ctx, goal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGoal", reflect.TypeOf((*MockGoalRepository)(nil).CreateGoal), ctx, goal)
}

// DeleteGoal mocks base method.
func (m *MockGoalRepository) DeleteGoal(ctx context.Context, userID, goalID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGoal", ctx, userID, goalID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGoal indicates an expected call of DeleteGoal.
func (mr *MockGoalRepositoryMockRecorder) DeleteGoal(ctx, userID, goalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGoal", reflect.TypeOf((*MockGoalRepository)(nil).DeleteGoal), ctx, userID, goalID)
}

// GetGoalByID mocks base method.
func (m *MockGoalRepository) GetGoalByID(ctx context.Context, userID, goalID string) (*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalByID", ctx, userID, goalID)
	ret0, _ := ret[0].(*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoalByID indicates an expected call of GetGoalByID.
func (mr *MockGoalRepositoryMockRecorder) GetGoalByID(ctx, userID, goalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalByID", reflect.TypeOf((*MockGoalRepository)(nil).GetGoalByID), ctx, userID, goalID)
}

// ListGoals mocks base method.
func (m *MockGoalRepository) ListGoals(ctx context.Context, filter interfaces.GoalListFilter) ([]*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGoals", ctx, filter)
	ret0, _ := ret[0].([]*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGoals indicates an expected call of ListGoals.
func (mr *MockGoalRepositoryMockRecorder) ListGoals(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGoals", reflect.TypeOf((*MockGoalRepository)(nil).ListGoals), ctx, filter)
}

// UpdateGoal mocks base method.
func (m *MockGoalRepository) UpdateGoal(ctx context.Context, goal *domain.Goal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoal", ctx, goal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGoal indicates an expected call of UpdateGoal.
func (mr *MockGoalRepositoryMockRecorder) UpdateGoal(ctx, goal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoal", reflect.TypeOf((*MockGoalRepository)(nil).UpdateGoal), ctx, goal)
}

// MockGoalContributionRepository is a mock of GoalContributionRepository interface.
type MockGoalContributionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGoalContributionRepositoryMockRecorder
	isgomock struct{}
}

// MockGoalContributionRepositoryMockRecorder is the mock recorder for MockGoalContributionRepository.
type MockGoalContributionRepositoryMockRecorder struct {
	mock *MockGoalContributionRepository
}

// NewMockGoalContributionRepository creates a new mock instance.
func NewMockGoalContributionRepository(ctrl *gomock.Controller) *MockGoalContributionRepository {
	mock := &MockGoalContributionRepository{ctrl: ctrl}
	mock.recorder = &MockGoalContributionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoalContributionRepository) EXPECT() *MockGoalContributionRepositoryMockRecorder {
	return m.recorder
}

// CreateContribution mocks base method.
func (m *MockGoalContributionRepository) CreateContribution(ctx context.Context, contribution *domain.GoalContribution) (*domain.GoalContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContribution", ctx, contribution)
	ret0, _ := ret[0].(*domain.GoalContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContribution indicates an expected call of CreateContribution.
func (mr *MockGoalContributionRepositoryMockRecorder) CreateContribution(ctx, contribution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContribution", reflect.TypeOf((*MockGoalContributionRepository)(nil).CreateContribution), ctx, contribution)
}

// GetTotalContributedAmount mocks base method.
func (m *MockGoalContributionRepository) GetTotalContributedAmount(ctx context.Context, userID, goalID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalContributedAmount", ctx, userID, goalID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalContributedAmount indicates an expected call of GetTotalContributedAmount.
func (mr *MockGoalContributionRepositoryMockRecorder) GetTotalContributedAmount(ctx, userID, goalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalContributedAmount", reflect.TypeOf((*MockGoalContributionRepository)(nil).GetTotalContributedAmount), ctx, userID, goalID)
}

// ListContributions mocks base method.
func (m *MockGoalContributionRepository) ListContributions(ctx context.Context, userID, goalID string, pageSize, offset int) ([]*domain.GoalContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContributions", ctx, userID, goalID, pageSize, offset)
	ret0, _ := ret[0].([]*domain.GoalContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContributions indicates an expected call of ListContributions.
func (mr *MockGoalContributionRepositoryMockRecorder) ListContributions(ctx, userID, goalID, pageSize, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContributions", reflect.TypeOf((*MockGoalContributionRepository)(nil).ListContributions), ctx, userID, goalID, pageSize, offset)
}
