// Code generated by MockGen. DO NOT EDIT.
// Source: internal/expenses/usecase/interfaces/input_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/expenses/usecase/interfaces/input_port.go -destination=internal/expenses/usecase/interfaces/mocks/input_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/chuuch/expense-tracker-backend/internal/expenses/domain"
	interfaces "github.com/chuuch/expense-tracker-backend/internal/expenses/usecase/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockExpenseUsecase is a mock of ExpenseUsecase interface.
type MockExpenseUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseUsecaseMockRecorder
	isgomock struct{}
}

// MockExpenseUsecaseMockRecorder is the mock recorder for MockExpenseUsecase.
type MockExpenseUsecaseMockRecorder struct {
	mock *MockExpenseUsecase
}

// NewMockExpenseUsecase creates a new mock instance.
func NewMockExpenseUsecase(ctrl *gomock.Controller) *MockExpenseUsecase {
	mock := &MockExpenseUsecase{ctrl: ctrl}
	mock.recorder = &MockExpenseUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseUsecase) EXPECT() *MockExpenseUsecaseMockRecorder {
	return m.recorder
}

// CreateExpense mocks base method.
func (m *MockExpenseUsecase) CreateExpense(ctx context.Context, userID string, amount int64, currency string, category domain.ExpenseCategory, description string, date time.Time) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExpense", ctx, userID, amount, currency, category, description, date)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExpense indicates an expected call of CreateExpense.
func (mr *MockExpenseUsecaseMockRecorder) CreateExpense(ctx, userID, amount, currency, category, description, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpense", reflect.TypeOf((*MockExpenseUsecase)(nil).CreateExpense), ctx, userID, amount, currency, category, description, date)
}

// DeleteExpense mocks base method.
func (m *MockExpenseUsecase) DeleteExpense(ctx context.Context, userID, expenseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpense", ctx, userID, expenseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpense indicates an expected call of DeleteExpense.
func (mr *MockExpenseUsecaseMockRecorder) DeleteExpense(ctx, userID, expenseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpense", reflect.TypeOf((*MockExpenseUsecase)(nil).DeleteExpense), ctx, userID, expenseID)
}

// GetExpenseByID mocks base method.
func (m *MockExpenseUsecase) GetExpenseByID(ctx context.Context, userID, expenseID string) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenseByID", ctx, userID, expenseID)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpenseByID indicates an expected call of GetExpenseByID.
func (mr *MockExpenseUsecaseMockRecorder) GetExpenseByID(ctx, userID, expenseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenseByID", reflect.TypeOf((*MockExpenseUsecase)(nil).GetExpenseByID), ctx, userID, expenseID)
}

// ListExpenses mocks base method.
func (m *MockExpenseUsecase) ListExpenses(ctx context.Context, filter interfaces.ExpenseListFilter) ([]*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpenses", ctx, filter)
	ret0, _ := ret[0].([]*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpenses indicates an expected call of ListExpenses.
func (mr *MockExpenseUsecaseMockRecorder) ListExpenses(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpenses", reflect.TypeOf((*MockExpenseUsecase)(nil).ListExpenses), ctx, filter)
}

// UpdateExpense mocks base method.
func (m *MockExpenseUsecase) UpdateExpense(ctx context.Context, userID, expenseID string, amount int64, currency domain.ExpenseCategory, description string, date time.Time) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpense", ctx, userID, expenseID, amount, currency, description, date)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExpense indicates an expected call of UpdateExpense.
func (mr *MockExpenseUsecaseMockRecorder) UpdateExpense(ctx, userID, expenseID, amount, currency, description, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpense", reflect.TypeOf((*MockExpenseUsecase)(nil).UpdateExpense), ctx, userID, expenseID, amount, currency, description, date)
}
