// Code generated by MockGen. DO NOT EDIT.
// Source: internal/expenses/usecase/interfaces/output_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/expenses/usecase/interfaces/output_port.go -destination=internal/expenses/usecase/interfaces/mocks/output_port_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/chuuch/expense-tracker-backend/internal/expenses/domain"
	interfaces "github.com/chuuch/expense-tracker-backend/internal/expenses/usecase/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockExpenseRepository is a mock of ExpenseRepository interface.
type MockExpenseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseRepositoryMockRecorder
	isgomock struct{}
}

// MockExpenseRepositoryMockRecorder is the mock recorder for MockExpenseRepository.
type MockExpenseRepositoryMockRecorder struct {
	mock *MockExpenseRepository
}

// NewMockExpenseRepository creates a new mock instance.
func NewMockExpenseRepository(ctrl *gomock.Controller) *MockExpenseRepository {
	mock := &MockExpenseRepository{ctrl: ctrl}
	mock.recorder = &MockExpenseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseRepository) EXPECT() *MockExpenseRepositoryMockRecorder {
	return m.recorder
}

// CreateExpense mocks base method.
func (m *MockExpenseRepository) CreateExpense(ctx context.Context, expense *domain.Expense) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExpense", ctx, expense)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExpense indicates an expected call of CreateExpense.
func (mr *MockExpenseRepositoryMockRecorder) CreateExpense(ctx, expense any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpense", reflect.TypeOf((*MockExpenseRepository)(nil).CreateExpense), ctx, expense)
}

// DeleteExpense mocks base method.
func (m *MockExpenseRepository) DeleteExpense(ctx context.Context, userID, expenseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpense", ctx, userID, expenseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpense indicates an expected call of DeleteExpense.
func (mr *MockExpenseRepositoryMockRecorder) DeleteExpense(ctx, userID, expenseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpense", reflect.TypeOf((*MockExpenseRepository)(nil).DeleteExpense), ctx, userID, expenseID)
}

// GetExpenseByID mocks base method.
func (m *MockExpenseRepository) GetExpenseByID(ctx context.Context, userID, expenseID string) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenseByID", ctx, userID, expenseID)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpenseByID indicates an expected call of GetExpenseByID.
func (mr *MockExpenseRepositoryMockRecorder) GetExpenseByID(ctx, userID, expenseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenseByID", reflect.TypeOf((*MockExpenseRepository)(nil).GetExpenseByID), ctx, userID, expenseID)
}

// ListExpenses mocks base method.
func (m *MockExpenseRepository) ListExpenses(ctx context.Context, filter interfaces.ExpenseListFilter) ([]*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpenses", ctx, filter)
	ret0, _ := ret[0].([]*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpenses indicates an expected call of ListExpenses.
func (mr *MockExpenseRepositoryMockRecorder) ListExpenses(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpenses", reflect.TypeOf((*MockExpenseRepository)(nil).ListExpenses), ctx, filter)
}

// UpdateExpense mocks base method.
func (m *MockExpenseRepository) UpdateExpense(ctx context.Context, expense *domain.Expense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpense", ctx, expense)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExpense indicates an expected call of UpdateExpense.
func (mr *MockExpenseRepositoryMockRecorder) UpdateExpense(ctx, expense any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpense", reflect.TypeOf((*MockExpenseRepository)(nil).UpdateExpense), ctx, expense)
}
