// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package postgresdb

import (
	"context"
	"time"
)

const getMonthlySpending = `-- name: GetMonthlySpending :many
SELECT to_char(date_trunc('month', date), 'YYYY-MM') AS year_month, 
SUM(amount) AS amount, currency 
FROM expenses 
WHERE user_id = $1
AND date >= $2 
AND date < ($3 + INTERVAL '1 month') 
GROUP BY year_month, currency 
ORDER BY year_month ASC
`

type GetMonthlySpendingParams struct {
	UserID   string      `json:"user_id"`
	FromDate time.Time   `json:"from_date"`
	ToDate   interface{} `json:"to_date"`
}

type GetMonthlySpendingRow struct {
	YearMonth string `json:"year_month"`
	Amount    int64  `json:"amount"`
	Currency  string `json:"currency"`
}

func (q *Queries) GetMonthlySpending(ctx context.Context, arg GetMonthlySpendingParams) ([]GetMonthlySpendingRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlySpending, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlySpendingRow
	for rows.Next() {
		var i GetMonthlySpendingRow
		if err := rows.Scan(&i.YearMonth, &i.Amount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendingByCategory = `-- name: GetSpendingByCategory :many
SELECT 
category::text AS category,
SUM(amount) AS amount, currency 
FROM expenses 
WHERE user_id = $1
AND date >= $2 
AND date <= $3 
GROUP BY category, currency 
ORDER BY amount DESC
`

type GetSpendingByCategoryParams struct {
	UserID   string    `json:"user_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type GetSpendingByCategoryRow struct {
	Category string `json:"category"`
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

func (q *Queries) GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpendingByCategory, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpendingByCategoryRow
	for rows.Next() {
		var i GetSpendingByCategoryRow
		if err := rows.Scan(&i.Category, &i.Amount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
