// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense.sql

package postgresdb

import (
	"context"
	"time"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    id,
    user_id,
    amount,
    currency,
    category,
    description,
    date,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, amount, currency, category, description, date, created_at, updated_at
`

type CreateExpenseParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.Date,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, user_id, amount, currency, category, description, date, created_at, updated_at 
FROM expenses 
WHERE id = $1 
AND user_id = $2 
LIMIT 1
`

type GetExpenseByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByID, arg.ID, arg.UserID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, user_id, amount, currency, category, description, date, created_at, updated_at 
FROM expenses 
WHERE user_id = $1 
AND ($2::text IS NULL OR category = $2) 
AND ($3::timestamptz IS NULL OR date >= $3) 
AND ($4::timestamptz IS NULL OR date <= $4) 
ORDER BY date DESC, created_at DESC 
LIMIT $5 OFFSET $6
`

type ListExpensesParams struct {
	UserID  string    `json:"user_id"`
	Column2 string    `json:"column_2"`
	Column3 time.Time `json:"column_3"`
	Column4 time.Time `json:"column_4"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :exec
UPDATE expenses 
SET
 amount = $3,
 currency = $4,
 category = $5,
 description = $6,
 date = $7,
 updated_at = $8 
WHERE id = $1 AND user_id = $2
`

type UpdateExpenseParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error {
	_, err := q.db.ExecContext(ctx, updateExpense,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.Date,
		arg.UpdatedAt,
	)
	return err
}
