// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goal.sql

package postgresdb

import (
	"context"
	"database/sql"
	"time"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
    id,
    user_id,
    name,
    currency,
    target_amount,
    target_date,
    status,
    created_at,
    updated_at,
    completed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, name, currency, target_amount, target_date, status, created_at, updated_at, completed_at
`

type CreateGoalParams struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	Name         string       `json:"name"`
	Currency     string       `json:"currency"`
	TargetAmount int64        `json:"target_amount"`
	TargetDate   sql.NullTime `json:"target_date"`
	Status       string       `json:"status"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	CompletedAt  sql.NullTime `json:"completed_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Currency,
		arg.TargetAmount,
		arg.TargetDate,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.TargetAmount,
		&i.TargetDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createGoalContribution = `-- name: CreateGoalContribution :one
INSERT INTO goal_contributions (
    id,
    goal_id,
    user_id,
    amount,
    contribution_date,
    note,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, goal_id, user_id, amount, contribution_date, note, created_at, updated_at
`

type CreateGoalContributionParams struct {
	ID               string         `json:"id"`
	GoalID           string         `json:"goal_id"`
	UserID           string         `json:"user_id"`
	Amount           int64          `json:"amount"`
	ContributionDate time.Time      `json:"contribution_date"`
	Note             sql.NullString `json:"note"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) CreateGoalContribution(ctx context.Context, arg CreateGoalContributionParams) (GoalContribution, error) {
	row := q.db.QueryRowContext(ctx, createGoalContribution,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.Amount,
		arg.ContributionDate,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Amount,
		&i.ContributionDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, user_id, name, currency, target_amount, target_date, status, created_at, updated_at, completed_at 
FROM goals 
WHERE id = $1 
AND user_id = $2 
LIMIT 1
`

type GetGoalByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByID, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.TargetAmount,
		&i.TargetDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTotalContributedAmount = `-- name: GetTotalContributedAmount :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total 
FROM goal_contributions 
WHERE user_id = $1 AND goal_id = $2
`

type GetTotalContributedAmountParams struct {
	UserID string `json:"user_id"`
	GoalID string `json:"goal_id"`
}

func (q *Queries) GetTotalContributedAmount(ctx context.Context, arg GetTotalContributedAmountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalContributedAmount, arg.UserID, arg.GoalID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listGoalContributions = `-- name: ListGoalContributions :many
SELECT id, goal_id, user_id, amount, contribution_date, note, created_at, updated_at 
FROM goal_contributions 
WHERE user_id = $1 AND goal_id = $2 
ORDER BY contribution_date DESC, created_at DESC 
LIMIT $3 
OFFSET $4
`

type ListGoalContributionsParams struct {
	UserID string `json:"user_id"`
	GoalID string `json:"goal_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListGoalContributions(ctx context.Context, arg ListGoalContributionsParams) ([]GoalContribution, error) {
	rows, err := q.db.QueryContext(ctx, listGoalContributions,
		arg.UserID,
		arg.GoalID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalContribution
	for rows.Next() {
		var i GoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Amount,
			&i.ContributionDate,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, name, currency, target_amount, target_date, status, created_at, updated_at, completed_at 
FROM goals 
WHERE user_id = $1 
AND ($2::text IS NULL OR status = $2) 
ORDER BY created_at DESC 
LIMIT $4 
OFFSET $3
`

type ListGoalsParams struct {
	UserID     string         `json:"user_id"`
	Status     sql.NullString `json:"status"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoals,
		arg.UserID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.TargetAmount,
			&i.TargetDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE goals 
SET 
    name = $3,
    target_amount = $4,
    target_date = $5,
    status = $6,
    updated_at = $7,
    completed_at = $8 
WHERE id = $1 AND user_id = $2
`

type UpdateGoalParams struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	Name         string       `json:"name"`
	TargetAmount int64        `json:"target_amount"`
	TargetDate   sql.NullTime `json:"target_date"`
	Status       string       `json:"status"`
	UpdatedAt    time.Time    `json:"updated_at"`
	CompletedAt  sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.ExecContext(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.TargetDate,
		arg.Status,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}
