// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Goal struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	Name         string       `json:"name"`
	Currency     string       `json:"currency"`
	TargetAmount int64        `json:"target_amount"`
	TargetDate   sql.NullTime `json:"target_date"`
	Status       string       `json:"status"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	CompletedAt  sql.NullTime `json:"completed_at"`
}

type GoalContribution struct {
	ID               string         `json:"id"`
	GoalID           string         `json:"goal_id"`
	UserID           string         `json:"user_id"`
	Amount           int64          `json:"amount"`
	ContributionDate time.Time      `json:"contribution_date"`
	Note             sql.NullString `json:"note"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type RefreshToken struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	TokenHash  string         `json:"token_hash"`
	ExpiresAt  time.Time      `json:"expires_at"`
	RevokedAt  sql.NullTime   `json:"revoked_at"`
	ReplacedBy sql.NullString `json:"replaced_by"`
	CreatedAt  time.Time      `json:"created_at"`
}

type User struct {
	ID                        string         `json:"id"`
	Email                     string         `json:"email"`
	PasswordHash              string         `json:"password_hash"`
	IsMfaEnabled              bool           `json:"is_mfa_enabled"`
	VerificationCode          sql.NullString `json:"verification_code"`
	VerificationCodeExpiresAt sql.NullTime   `json:"verification_code_expires_at"`
	Role                      string         `json:"role"`
	Status                    string         `json:"status"`
	Username                  string         `json:"username"`
	Phone                     string         `json:"phone"`
	Address                   string         `json:"address"`
	City                      string         `json:"city"`
	State                     string         `json:"state"`
	Zip                       string         `json:"zip"`
	Country                   string         `json:"country"`
	CreatedAt                 time.Time      `json:"created_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
	LastLoginAt               sql.NullTime   `json:"last_login_at"`
	DeletedAt                 sql.NullTime   `json:"deleted_at"`
}
