// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgresdb

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, password_hash, is_mfa_enabled, role, status,
    username, verification_code, verification_code_expires_at,
    created_at, updated_at, last_login_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13
) RETURNING id, email, password_hash, is_mfa_enabled, verification_code, verification_code_expires_at, role, status, username, created_at, updated_at, last_login_at, deleted_at
`

type CreateUserParams struct {
	ID                        string         `json:"id"`
	Email                     string         `json:"email"`
	PasswordHash              string         `json:"password_hash"`
	IsMfaEnabled              bool           `json:"is_mfa_enabled"`
	Role                      string         `json:"role"`
	Status                    string         `json:"status"`
	Username                  string         `json:"username"`
	VerificationCode          sql.NullString `json:"verification_code"`
	VerificationCodeExpiresAt sql.NullTime   `json:"verification_code_expires_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
	LastLoginAt               sql.NullTime   `json:"last_login_at"`
	DeletedAt                 sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.IsMfaEnabled,
		arg.Role,
		arg.Status,
		arg.Username,
		arg.VerificationCode,
		arg.VerificationCodeExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
		arg.DeletedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsMfaEnabled,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.Role,
		&i.Status,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_mfa_enabled, verification_code, verification_code_expires_at, role, status, username, created_at, updated_at, last_login_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsMfaEnabled,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.Role,
		&i.Status,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, is_mfa_enabled, verification_code, verification_code_expires_at, role, status, username, created_at, updated_at, last_login_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsMfaEnabled,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.Role,
		&i.Status,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET email = $2, password_hash = $3, is_mfa_enabled = $4, role = $5, status = $6,
    username = $7, verification_code = $8, verification_code_expires_at = $9,
    updated_at = $10, last_login_at = $11
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	ID                        string         `json:"id"`
	Email                     string         `json:"email"`
	PasswordHash              string         `json:"password_hash"`
	IsMfaEnabled              bool           `json:"is_mfa_enabled"`
	Role                      string         `json:"role"`
	Status                    string         `json:"status"`
	Username                  string         `json:"username"`
	VerificationCode          sql.NullString `json:"verification_code"`
	VerificationCodeExpiresAt sql.NullTime   `json:"verification_code_expires_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
	LastLoginAt               sql.NullTime   `json:"last_login_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.IsMfaEnabled,
		arg.Role,
		arg.Status,
		arg.Username,
		arg.VerificationCode,
		arg.VerificationCodeExpiresAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	return err
}
